version: '3.5'
services:

  postgres:
    container_name: pp_postgres
    image: postgres:latest
    env_file: .db.env
    ports:
      - 5432:5432  
    volumes:
      - ./db_volume:/var/lib/postgresql/data
  
  web:
    build: .
    restart: always
    container_name: pp_web
    command: gunicorn --bind 0.0.0.0:5000 app.wsgi:app
    env_file: .env
    ports:
      - 5000:5000  
    depends_on:
      - postgres

volumes:
  db_volume:
