"""empty message

Revision ID: faf6bd7194dd
Revises: 
Create Date: 2022-08-20 23:33:17.292424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf6bd7194dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=12), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plates_created'), 'plates', ['created'], unique=False)
    op.execute("CREATE EXTENSION fuzzystrmatch;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plates_created'), table_name='plates')
    op.drop_table('plates')
    # ### end Alembic commands ###
